stages:
  download_SGFF:
    cmd: scp -r -C "\${SSH_USERNAME}@olympus.atmos.uw.edu:/home/disk/eos5/rmeast/FFGS_Class/yearly/Daily*" data/input/SGFF/yearly/
    outs:
    - data/input/SGFF/yearly/
  merge_yearly_SGFF:
    cmd: python scripts/concat_chunk.py -i "data/input/SGFF/yearly/*" -o data/output/Daily_1x1_SGFF_MODIS-IR_NorthAtlantic.zarr
    deps:
    - data/input/SGFF/yearly
    - scripts/concat_chunk.py
    outs:
    - data/output/Daily_1x1_SGFF_MODIS-IR_NorthAtlantic.zarr
